FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci

COPY . .
CMD ["npm", "start"]

# to create a volume locally and see any change live in the react app...

# docker run --rm -d -p 3000:3000 -v ./public:/app/public -v ./src:/app/src react-app:dev